# .rubocop.yml
AllCops:
  DisabledByDefault: true
  Exclude:
    - 'gems/**/*'
    # NewCops: disable
Bundler:
  Enabled: true
Gemspec:
  Enabled: true
Layout:
  Enabled: true
Lint:
  Enabled: true
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true
Metrics:
  Enabled: false
Migration:
  Enabled: false
Naming:
  Enabled: true
Security:
  Enabled: true
Style:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
